version: "1.0"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_HOST
      - MYSQL_PORT
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DBNAME
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - todo-mysql-data:/var/lib/mysql
      - todo-mysql-config:/etc/mysql

  node_backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_DBNAME: ${MYSQL_DBNAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: db
    volumes:
      - ./:/nodejs_hello
    ports:
      - "3030:3030"
    depends_on:
      - db

volumes:
  todo-mysql-data:
  todo-mysql-config: